apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chaima-belhedi/crossplane-mrap-poc.git'
    targetRevision: main
    path: '.'  # repo root
    helm:
      releaseName: crossplane
      values: |
        image:
          tag: v1.20.1    # baseline version
        args:
          - --enable-usages
          - --enable-ssa-claims
        metrics:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
